apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ template "agentEnv.fullname" $ -}}-sandbox-egress
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  description: |
    Allow egress only to cluster-wide DNS, everything in the sandbox, and any allowDomains.
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: {{ .Release.Namespace }}
      {{- include "agentEnv.selectorLabels" $ | nindent 6 }}
  egress:
    - toEndpoints:
      - matchLabels:
          io.kubernetes.pod.namespace: kube-system
          k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
      - matchLabels:
          io.kubernetes.pod.namespace: {{ .Release.Namespace }}
          {{- include "agentEnv.selectorLabels" $ | nindent 10 }}
    {{- if .Values.allowDomains }}
    - toFQDNs:
    {{- range .Values.allowDomains }}
      - matchPattern: "{{ . }}"
    {{- end }}
    {{- end }}
    {{- with .Values.allowEntities }}
    - toEntities:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.allowCIDR }}
    - toCIDR:
      {{- toYaml . | nindent 6 }}
    {{- end }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ template "agentEnv.fullname" $ -}}-sandbox-default-deny-ingress
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  description: Default deny ingress. Allow other policies to be more specific.
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: {{ .Release.Namespace }}
      {{- include "agentEnv.selectorLabels" $ | nindent 6 }}
  ingress:
    - {}
{{- if .Values.networks }}
{{- range $networkName, $networkConfig := .Values.networks }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ template "agentEnv.fullname" $ }}-sandbox-{{ $networkName }}-ingress
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  description: |
    Allow ingress from other pods in the "{{ $networkName }}" agent sandbox "network".
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: {{ $.Release.Namespace }}
      {{- include "agentEnv.selectorLabels" $ | nindent 6 }}
      aisi.gov.uk/network-{{ $networkName }}: "true"
  ingress:
    - fromEndpoints:
      - matchLabels:
          io.kubernetes.pod.namespace: {{ $.Release.Namespace }}
          aisi.gov.uk/network-{{ $networkName }}: "true"
          {{- include "agentEnv.selectorLabels" $ | nindent 10 }}
{{- end }}
{{- else }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ template "agentEnv.fullname" $ }}-sandbox-ingress
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  description: |
    Allow ingress from other pods in the same agent sandbox.
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: {{ .Release.Namespace }}
      {{- include "agentEnv.selectorLabels" $ | nindent 6 }}
  ingress:
    - fromEndpoints:
      - matchLabels:
          io.kubernetes.pod.namespace: {{ .Release.Namespace }}
          {{- include "agentEnv.selectorLabels" $ | nindent 10 }}
{{- end }}
